module.exports = [
  {key: "US", label: "United States of America"},
  {key: "DE", label: "Germany"},
  {key: "UK", label: "United Kingdom"},
  {key: "CA", label: "Canada"},
  {key: "AU", label: "Australia"},
  {key: "FR", label: "France"},
  {key: "IT", label: "Italy"},
  {key: "ES", label: "Spain"},
  {key: "FI", label: "Finland"},
  {key: "NO", label: "Norway"},
  {key: "SE", label: "Sweden"},
  {key: "DK", label: "Denmark"},
  {key: "BR", label: "Brazil"},
  {key: "PT", label: "Portugal"},
  {key: "AT", label: "Austria"},
  {key: "CH", label: "Switzerland"},
  {key: "IN", label: "India"},
  {key: "AD", label: "Andorra"},
  {key: "AF", label: "Afghanistan"},
  {key: "AL", label: "Albania"},
  {key: "DZ", label: "Algeria"},
  {key: "AS", label: "American Samoa"},
  {key: "VI", label: "American Virgin Islands"},
  {key: "AO", label: "Angola"},
  {key: "AI", label: "Anguilla"},
  {key: "AQ", label: "Antarctic"},
  {key: "AG", label: "Antigua and Barbuda"},
  {key: "AR", label: "Argentina"},
  {key: "AM", label: "Armenia"},
  {key: "AW", label: "Aruba"},
  {key: "AZ", label: "Azerbaijan"},
  {key: "BS", label: "Bahamas"},
  {key: "BH", label: "Bahrain"},
  {key: "BD", label: "Bangladesh"},
  {key: "BB", label: "Barbados"},
  {key: "BY", label: "Belarus"},
  {key: "BE", label: "Belgium"},
  {key: "BZ", label: "Belize"},
  {key: "BJ", label: "Benin"},
  {key: "BM", label: "Bermudas"},
  {key: "BT", label: "Bhutan"},
  {key: "BO", label: "Bolivia"},
  {key: "BA", label: "Bosnia-Herzegovina"},
  {key: "BW", label: "Botswana"},
  {key: "BV", label: "Bouvet Island"},
  {key: "IO", label: "British Indian Ocean"},
  {key: "VG", label: "British Virgin Islands"},
  {key: "BN", label: "Brunei"},
  {key: "BG", label: "Bulgaria"},
  {key: "BF", label: "Burkina Faso"},
  {key: "MM", label: "Burma"},
  {key: "BI", label: "Burundi"},
  {key: "KH", label: "Cambodia"},
  {key: "CM", label: "Cameroons"},
  {key: "CV", label: "Cape Verde"},
  {key: "KY", label: "Cayman Islands"},
  {key: "CF", label: "Central African Republic"},
  {key: "TD", label: "Chad"},
  {key: "CL", label: "Chile"},
  {key: "CN", label: "China"},
  {key: "CX", label: "Christmas Island"},
  {key: "CC", label: "Cocos Islands"},
  {key: "CO", label: "Colombia"},
  {key: "KM", label: "Comoros"},
  {key: "CG", label: "Congo"},
  {key: "CK", label: "Cook Islands"},
  {key: "CR", label: "Costa Rica"},
  {key: "HR", label: "Croatia"},
  {key: "CU", label: "Cuba"},
  {key: "CY", label: "Cyprus"},
  {key: "CZ", label: "Czech Republic"},
  {key: "CD", label: "Democratic Republic of Congo"},
  {key: "DJ", label: "Djibouti"},
  {key: "DM", label: "Dominica"},
  {key: "DO", label: "Dominican Republic"},
  {key: "EC", label: "Ecuador"},
  {key: "EG", label: "Egypt"},
  {key: "SV", label: "El Salvador"},
  {key: "GQ", label: "Equatorial Guinea"},
  {key: "ER", label: "Eritrea"},
  {key: "EE", label: "Estonia"},
  {key: "ET", label: "Ethiopia"},
  {key: "FK", label: "Falkland Islands"},
  {key: "FO", label: "Faroe Islands"},
  {key: "FJ", label: "Fiji"},
  {key: "GF", label: "French Guyana"},
  {key: "PF", label: "French Polynesia"},
  {key: "TF", label: "French Southern Territories"},
  {key: "GA", label: "Gabon"},
  {key: "GM", label: "Gambia"},
  {key: "GE", label: "Georgia"},
  {key: "GH", label: "Ghana"},
  {key: "GI", label: "Gibraltar"},
  {key: "GR", label: "Greece"},
  {key: "GL", label: "Greenland"},
  {key: "GD", label: "Grenada"},
  {key: "GP", label: "Guadeloupe"},
  {key: "GU", label: "Guam"},
  {key: "GT", label: "Guatemala"},
  {key: "GN", label: "Guinea"},
  {key: "GW", label: "Guinea Bissau"},
  {key: "GY", label: "Guyana"},
  {key: "HT", label: "Haiti"},
  {key: "HM", label: "Heard Island and McDonald Islands"},
  {key: "HN", label: "Honduras"},
  {key: "HK", label: "Hong Kong"},
  {key: "HU", label: "Hungary"},
  {key: "IS", label: "Iceland"},
  {key: "ID", label: "Indonesia"},
  {key: "IR", label: "Iran"},
  {key: "IQ", label: "Iraq"},
  {key: "IE", label: "Ireland"},
  {key: "IL", label: "Israel"},
  {key: "CI", label: "Ivory Coast"},
  {key: "JM", label: "Jamaica"},
  {key: "JP", label: "Japan"},
  {key: "JO", label: "Jordan"},
  {key: "KZ", label: "Kazakhstan"},
  {key: "KE", label: "Kenya"},
  {key: "KI", label: "Kiribati"},
  {key: "KW", label: "Kuwait"},
  {key: "KG", label: "Kyrgyzstan"},
  {key: "LA", label: "Laos"},
  {key: "LV", label: "Latvia"},
  {key: "LB", label: "Lebanon"},
  {key: "LS", label: "Lesotho"},
  {key: "LR", label: "Liberia"},
  {key: "LY", label: "Libya"},
  {key: "LI", label: "Liechtenstein"},
  {key: "LT", label: "Lithuania"},
  {key: "LU", label: "Luxembourg"},
  {key: "MO", label: "Macao"},
  {key: "MK", label: "Macedonia"},
  {key: "MG", label: "Madagascar"},
  {key: "MW", label: "Malawi"},
  {key: "MY", label: "Malaysia"},
  {key: "MV", label: "Maldives"},
  {key: "ML", label: "Mali"},
  {key: "MT", label: "Malta"},
  {key: "MP", label: "Mariana"},
  {key: "MH", label: "Marshall Islands"},
  {key: "MQ", label: "Martinique"},
  {key: "MR", label: "Mauritania"},
  {key: "MU", label: "Mauritius"},
  {key: "YT", label: "Mayotte"},
  {key: "MX", label: "Mexico"},
  {key: "FM", label: "Micronesia"},
  {key: "MZ", label: "Mocambique"},
  {key: "MD", label: "Moldova"},
  {key: "MC", label: "Monaco"},
  {key: "MN", label: "Mongolia"},
  {key: "MS", label: "Montserrat"},
  {key: "MA", label: "Morocco"},
  {key: "NA", label: "Namibia"},
  {key: "NR", label: "Nauru"},
  {key: "NP", label: "Nepal"},
  {key: "NL", label: "Netherlands"},
  {key: "AN", label: "Netherlands Antilles"},
  {key: "NC", label: "New Caledonia"},
  {key: "NZ", label: "New Zealand"},
  {key: "NI", label: "Nicaragua"},
  {key: "NE", label: "Niger"},
  {key: "NG", label: "Nigeria"},
  {key: "NU", label: "Niue"},
  {key: "NF", label: "Norfolk Islands"},
  {key: "KP", label: "North Korea"},
  {key: "OM", label: "Oman"},
  {key: "PK", label: "Pakistan"},
  {key: "PW", label: "Palau"},
  {key: "PS", label: "Palestine"},
  {key: "PA", label: "Panama"},
  {key: "PG", label: "Papua New Guinea"},
  {key: "PY", label: "Paraguay"},
  {key: "PE", label: "Peru"},
  {key: "PH", label: "Philippines"},
  {key: "PN", label: "Pitcairn"},
  {key: "PL", label: "Poland"},
  {key: "PR", label: "Puerto Rico"},
  {key: "QA", label: "Qatar"},
  {key: "RE", label: "Reunion"},
  {key: "RO", label: "Romania"},
  {key: "RU", label: "Russia"},
  {key: "RW", label: "Rwanda"},
  {key: "LC", label: "Saint Lucia"},
  {key: "PM", label: "Saint Pierre and Miquelon"},
  {key: "WS", label: "Samoa"},
  {key: "SM", label: "San Marino"},
  {key: "ST", label: "Sao Tome"},
  {key: "SA", label: "Saudi Arabia"},
  {key: "SN", label: "Senegal"},
  {key: "SC", label: "Seychelles"},
  {key: "SL", label: "Sierra Leone"},
  {key: "SG", label: "Singapore"},
  {key: "SK", label: "Slovakia"},
  {key: "SI", label: "Slovenia"},
  {key: "SB", label: "Solomon Islands"},
  {key: "SO", label: "Somalia"},
  {key: "ZA", label: "South Africa"},
  {key: "GS", label: "South Georgia and the South Sandwich Islands"},
  {key: "KR", label: "South Korea"},
  {key: "LK", label: "Sri Lanka"},
  {key: "SH", label: "St. Helena"},
  {key: "KN", label: "St. Kitts Nevis Anguilla"},
  {key: "VC", label: "St. Vincent"},
  {key: "SD", label: "Sudan"},
  {key: "SR", label: "Suriname"},
  {key: "SJ", label: "Svalbard and Jan Mayen Islands"},
  {key: "SZ", label: "Swaziland"},
  {key: "SY", label: "Syria"},
  {key: "TW", label: "Taiwan"},
  {key: "TJ", label: "Tajikistan"},
  {key: "TZ", label: "Tanzania"},
  {key: "TH", label: "Thailand"},
  {key: "TP", label: "Timor"},
  {key: "TG", label: "Togo"},
  {key: "TK", label: "Tokelau"},
  {key: "TO", label: "Tonga"},
  {key: "TT", label: "Trinidad Tobago"},
  {key: "TN", label: "Tunisia"},
  {key: "TR", label: "Turkey"},
  {key: "TM", label: "Turkmenistan"},
  {key: "TC", label: "Turks and Caicos Islands"},
  {key: "TV", label: "Tuvalu"},
  {key: "UG", label: "Uganda"},
  {key: "UA", label: "Ukraine"},
  {key: "AE", label: "United Arab Emirates"},
  {key: "UY", label: "Uruguay"},
  {key: "UZ", label: "Uzbekistan"},
  {key: "VU", label: "Vanuatu"},
  {key: "VA", label: "Vatican"},
  {key: "VE", label: "Venezuela"},
  {key: "VN", label: "Vietnam"},
  {key: "WF", label: "Wallis and Futuna"},
  {key: "EH", label: "Western Sahara"},
  {key: "YE", label: "Yemen"},
  {key: "YU", label: "Yugoslavia"},
  {key: "ZM", label: "Zambia"},
  {key: "ZW", label: "Zimbabwe"}
];