module.exports = [
  {label:"Arts & Photography",key:"arts_photography"},
  {label:"Business",key:"business"},
  {label:"Crafts & Hobbies",key:"crafts_hobbies"},
  {label:"Design",key:"design"},
  {label:"Education",key:"education"},
  {label:"Games",key:"games"},
  {label:"Health & Fitness",key:"health_fitness"},
  {label:"Humanities",key:"humanities"},
  {label:"Languages",key:"languages"},
  {label:"Law",key:"law"},
  {label:"Lifestyle",key:"lifestyle"},
  {label:"Math & Science",key:"math_science"},
  {label:"Music",key:"music"},
  {label:"Other",key:"other"},
  {label:"Social Sciences",key:"social_sciences"},
  {label:"Sports",key:"sports"},
  {label:"Technology",key:"technology"},
  {label:"Test Preparation",key:"test"},
];